//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GariLagbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ContactUS_ID { get; set; }
        public string ContactUS_Name { get; set; }
        public int ContactUS_PhoneNo { get; set; }
        public string ContactUS_Email { get; set; }
        public string ContactUS_Message { get; set; }
    }
}
