//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GariLagbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerStatu
    {
        public int Status_ID { get; set; }
        public int Customer_ID { get; set; }
        public string Status_Time { get; set; }
        public string Satus_Date { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
