//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GariLagbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public int Order_ID { get; set; }
        public Nullable<double> Payment_Total { get; set; }
        public Nullable<double> Payment_Advance { get; set; }
        public Nullable<double> Payment_Due { get; set; }
    
        public virtual OrderM OrderM { get; set; }
    }
}
