//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GariLagbe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.OrderMs = new HashSet<OrderM>();
        }
    
        public int Vehicle_ID { get; set; }
        public int Category_ID { get; set; }
        public string Vehicle_Name { get; set; }
        public int Vehicle_LicenseNO { get; set; }
        public string Vehicle_Status { get; set; }
        public string Vehicle_Image { get; set; }
        public string Vehicle_Engine { get; set; }
        public Nullable<double> Vehicle_Price { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderM> OrderMs { get; set; }
    }
}
